### ISSUE TITLE
Site is not responsive

### ISSUE THREAD

**Issue by ppasq** [GeoNode/geonode.github.com#24]
Templates are currently based on Bootstrap 2.x version. To enable responsiveness there are basically two ways: add the proper meta tag (http://getbootstrap.com/2.3.2/scaffolding.html#responsive) or upgrade to Bootstrap 3.x version (which is mobile first). The first option requires some debugging while the latter implies to rewrite the page structure according to Bootstrap 3.x specifications.

**Comment by Rmcavin** [comment]
Does this issue still need work? I can help out if needed.
