### ISSUE TITLE
Please allow to change the default installation to localhost

### ISSUE THREAD

**Issue by ahmednosman** [GeoNode/geonode.github.com#34]
The localhost could be hosting other services, I suggest a default port of 8081 or similar, then informing the user at the final text note

**Comment by simod** [comment]
You mean GeoNode? It runs on apache and apache runs commonly on port 80.

**Comment by ahmednosman** [comment]
There is a very high chance the windows machine already running IIS, most windows setup have already IIS taking port 80.
Most common cases would be administrators adding geonode after they have installed IIS alread

**Comment by ahmednosman** [comment]
wrong project, this is in the windows installer
