### ISSUE TITLE
No need to present JVM heap for Geoserver

### ISSUE THREAD

**Issue by ahmednosman** [GeoNode/geonode.github.com#35]
This screen might not be something many users can understand, instead they can change after installion

**Comment by capooti** [comment]
Which screen?

**Comment by ahmednosman** [comment]
The wizard screen, 
Titled
Assign Java Virtual Machine Heap to GeoServer. 
The wizzard screen provides JVM min heap and JVM max heap listing 256 and 1024 as default values

**Comment by ahmednosman** [comment]
wrong project, this is in the windows installer
