### ISSUE TITLE
Quick start with Docker

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode.github.com#78]
As apt is currently not maintained maybe it would be a solution to set docker as quick start guide. The geonode project install is very easy to handle ... 
![bildschirmfoto 2019-01-03 um 19 53 02](https://user-images.githubusercontent.com/20478652/50655797-7b035000-0f91-11e9-84cd-77086a6ef1f3.png)

**Comment by afabiani** [comment]
+1
