### ISSUE TITLE
geonode.org bugs, content and visual representation.

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode.github.com#79]
---
1. Linked Document names 404 links at geonode.org which have to be fixed. 

- [deadlinks.pdf](https://github.com/GeoNode/geonode.github.com/files/3365779/deadlinks.pdf)

---
2. The **Quickstart has to be reviewed**. From a discussion at gitter (?) we're more or less agreed on docker? Which could look something like:

![50655797-7b035000-0f91-11e9-84cd-77086a6ef1f3](https://user-images.githubusercontent.com/20478652/60805046-4f9b3100-a17f-11e9-865a-92680acf576f.png)

---
3. The site should be responsive: See https://github.com/GeoNode/geonode.github.com/issues/24
---

**Comment by afabiani** [comment]
Thanks @t-book for the analysis.
For the 2.10 release let's be sure the most important links (docs, setup files) are functional. About the others, I agree the site would need some review. Maybe let's try to ask to the mailing list for volunteers as the GeoNode web-site content managers.

**Comment by t-book** [comment]
> For the 2.10 release let's be sure the most important links (docs, setup files) are functional. 

Okay, I will take care of this. 

> Maybe let's try to ask to the mailing list for volunteers as the GeoNode web-site content managers.

+1 !

**Comment by amefad** [comment]
I'll be glad to be part of the group

**Comment by t-book** [comment]
great @amefad 👍

**Comment by juliermegeotube** [comment]
Hi Toni and Alessio,
I will be glad to help. Count me in!!!

**Comment by juliermegeotube** [comment]
This link here [GeoNode Management Commands — GeoNode 2.10 documentation] needs information. I would like to contribute and information to site(http://docs.geonode.org/en/new-docs/admin/index.html)

**Comment by juliermegeotube** [comment]
...add information to the site

**Comment by afabiani** [comment]
Thanks @juliermegeotube 
please be careful that now we merged back the new-docs branch into master, so the most updated docs can be found here
http://docs.geonode.org/en/master/

The site http://docs.geonode.org/en/new-docs is no longer valid

**Comment by t-book** [comment]
I'm just updating some links which should at least make it a little better for 2.10 release as Alessio suggested.

Here some thoughts:
- I would welcome to not just fix the website but to rework it
- as we did with docs it would be helpful to create a spreadsheet at google first collecting site hierarchy and content, further it could be helpful to discuss

1. - Is the content correct or still accurate?
2. - Is anything missing?
3. - Is it useful to our readers?

- We could try to keep it small (manageable) – take what we need from the old page – rebuild the site on a new dev branch.

If you @amefad @juliermegeotube  @afabiani agree I could start with the spreadsheet and share the link so that you can join in?  @afabiani Needs the recreation be accepted from the PSC?

**Comment by afabiani** [comment]
Site links updated, no more 404 hopefully!

GeoNode Documentation it still uncomplete. Please always refer to the 2.10.x branch one http://docs.geonode.org/en/2.10.x

**Comment by juliermegeotube** [comment]
@t-book, let me know how can I help to update the links that you pointed in the draft.

Always here to help

**Comment by gannebamm** [comment]
Can this be closed?
