### ISSUE TITLE
multiple old docs links point to 2.10.x

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode.github.com#84]
After fixing #83 I realized there are many more links to old docs. Eg:

- [ ] Workshops
- [ ] Quick Installation Guide
- [ ] Full Installation Guide
- [ ] Read the Users Guide
- [ ] Read the Admins Guide
- [ ] Read the developer installation docs for a detailed step by step guide
- [ ] Blog >> Geonode 2.10 released >> Installation Guides

**Comment by t-book** [comment]
thanks @gannebamm we can set 301 at read the docs but we should definitly update the website as well.
