### ISSUE TITLE
Misalignment of content layout

### ISSUE THREAD

**Issue by jkariukidev** [GeoNode/geonode.github.com#97]
There is mis alignment of content layout after updating Bootstrap to version 5. 
![image](https://user-images.githubusercontent.com/23359514/171142012-5383f8f2-976a-4a98-ae73-135c00391eab.png)

**Comment by t-book** [comment]
Nicht im Büro zwischen 30.05. und 06.06 2022
Out of office between 30.05. and 06.06 2022

In dringenden Fällen kontaktieren Sie bitte ***@***.***
In urgent cases please contact ***@***.***


Toni Schönbuchner

-- 
+++++++++++++++++++++++++++++++++++++++++
Geoinformatik mit Open Source Technologie
+++++++++++++++++++++++++++++++++++++++++

CSGIS Gbr
Gottschedstraße 12
04109 Leipzig
